# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f37ea5d3274a88fe706d5a3b7812902a8578119190e2d5713dad11a80157fd3c76a198cc861b8fb82c5bf0337a903cf089fd31d51df5d1cd73d69263084bbb0

test:
  secret_key_base: 0dd1323c1a2dcc785557f400bab807396430ee74629c6d99f19bf3fa506bd9bbb55494941733c132fea4098239c303f5cd13c71e688a9d1e30e432393a30b1e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
